name: Resume Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image with tag
      run: docker build . --file Dockerfile --tag my-image-name:${{github.run_number}}
    - name: Build latest 
      run: docker build . --file Dockerfile --tag my-image-name
    - name: Login to Docker hub
      run: echo "${{secrets.PASSWORD}}" | docker login -u ${{secrets.USERNAME}} --password-stdin
    - name: tag image
      run: docker tag my-image-name:${{github.run_number}} ${{secrets.tatangcaron}}/my-image-name:${{github.run_number}}